// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"
	service "itk-test-task/iternal/service"

	mock "github.com/stretchr/testify/mock"
)

// WalletServiceInterface is an autogenerated mock type for the WalletServiceInterface type
type WalletServiceInterface struct {
	mock.Mock
}

// GetWalletById provides a mock function with given fields: ctx, walletID
func (_m *WalletServiceInterface) GetWalletById(ctx context.Context, walletID string) (int64, error) {
	ret := _m.Called(ctx, walletID)

	if len(ret) == 0 {
		panic("no return value specified for GetWalletById")
	}

	var r0 int64
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (int64, error)); ok {
		return rf(ctx, walletID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) int64); ok {
		r0 = rf(ctx, walletID)
	} else {
		r0 = ret.Get(0).(int64)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, walletID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateWallet provides a mock function with given fields: ctx, input
func (_m *WalletServiceInterface) UpdateWallet(ctx context.Context, input *service.UpdateWallet) error {
	ret := _m.Called(ctx, input)

	if len(ret) == 0 {
		panic("no return value specified for UpdateWallet")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *service.UpdateWallet) error); ok {
		r0 = rf(ctx, input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewWalletServiceInterface creates a new instance of WalletServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWalletServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *WalletServiceInterface {
	mock := &WalletServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
